# Use official Node image
FROM node:22-slim

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend/ .

RUN npm run build
RUN npm install -g serve
EXPOSE 4173

CMD ["serve", "-s", "dist", "-l", "4173"]