# Generated by Django 5.1.4 on 2025-02-14 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_name', models.CharField(max_length=50)),
                ('emotion_type', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='mood_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence_name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='influence_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('text_note', models.TextField(blank=True, null=True)),
                ('emotions', models.ManyToManyField(blank=True, to='diary.emotion')),
                ('influences', models.ManyToManyField(blank=True, to='diary.influence')),
                ('mood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
